export default [
  {
    id: "1",
    name: "A",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_A.png",
    audioSrc: "audio/alphabet/a.mp3",
    color: "jaune",
  },
  {
    id: "2",
    name: "B",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_B.png",
    audioSrc: "audio/alphabet/b.mp3",
    color: "vert",
  },
  {
    id: "3",
    name: "C",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_C.png",
    audioSrc: "audio/alphabet/c.mp3",
    color: "bordeaux",
  },
  {
    id: "4",
    name: "D",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_D.png",
    audioSrc: "audio/alphabet/d.mp3",
    color: "bleu",
  },
  {
    id: "5",
    name: "E",
    imgSrc: "IMGauthor/alphabet/aniamal_alphabet_E.png",
    audioSrc: "audio/alphabet/e.mp3",
    color: "orange",
  },
  {
    id: "6",
    name: "F",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_F.png",
    audioSrc: "audio/alphabet/f.mp3",
    color: "vert clair",
  },
  {
    id: "7",
    name: "G",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_G.png",
    audioSrc: "audio/alphabet/g.mp3",
    color: "jaune",
  },
  {
    id: "8",
    name: "H",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_H.png",
    audioSrc: "audio/alphabet/h.mp3",
    color: "violet",
  },
  {
    id: "9",
    name: "I",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_I.png",
    audioSrc: "audio/alphabet/i.mp3",
    color: "turquoise",
  },
  {
    id: "10",
    name: "J",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_J.png",
    audioSrc: "audio/alphabet/j.mp3",
    color: "rouge",
  },
  {
    id: "11",
    name: "K",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_K.png",
    audioSrc: "audio/alphabet/k.mp3",
    color: "",
  },
  {
    id: "12",
    name: "L",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_L.png",
    audioSrc: "audio/alphabet/l.mp3",
    color: "vert",
  },
  {
    id: "13",
    name: "M",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_M.png",
    audioSrc: "audio/alphabet/m.mp3",
    color: "rouge",
  },
  {
    id: "14",
    name: "N",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_N.png",
    audioSrc: "audio/alphabet/n.mp3",
    color: "turquoise",
  },
  {
    id: "15",
    name: "O",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_O.png",
    audioSrc: "audio/alphabet/o.mp3",
    color: "orange",
  },
  {
    id: "16",
    name: "P",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_P.png",
    audioSrc: "audio/alphabet/p.mp3",
    color: "vert clair",
  },
  {
    id: "17",
    name: "Q",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_Q.png",
    audioSrc: "audio/alphabet/q.mp3",
    color: "jaune",
  },
  {
    id: "18",
    name: "R",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_R.png",
    audioSrc: "audio/alphabet/r.mp3",
    color: "purple",
  },
  {
    id: "19",
    name: "S",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_S.png",
    audioSrc: "audio/alphabet/s.mp3",
    color: "bleu clair",
  },
  {
    id: "20",
    name: "T",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_T.png",
    audioSrc: "audio/alphabet/t.mp3",
    color: "rose orange",
  },
  {
    id: "21",
    name: "U",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_U.png",
    audioSrc: "audio/alphabet/u.mp3",
    color: "jaune",
  },
  {
    id: "22",
    name: "V",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_V.png",
    audioSrc: "audio/alphabet/v.mp3",
    color: "vert",
  },
  {
    id: "23",
    name: "W",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_W.png",
    audioSrc: "audio/alphabet/w.mp3",
    color: "rouge",
  },
  {
    id: "24",
    name: "X",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_X.png",
    audioSrc: "audio/alphabet/x.mp3",
    color: "bleu",
  },
  {
    id: "25",
    name: "Y",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_Y.png",
    audioSrc: "audio/alphabet/y.mp3",
    color: "orange",
  },
  {
    id: "26",
    name: "Z",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_Z.png",
    audioSrc: "audio/alphabet/z.mp3",
    color: "vert clair",
  },
]
