const SAVANE = [
  {
    id: "1",
    name: "lion",
    imgSrc: "assets/IMGauthor/SAVANE/lion.jpg",
    audioSrc: "assets/audio/SAVANE/lion.mp3",
    color: "jaune",
    english: "lion",
    french:
      "Les lion vivent en groupe de femelles souvent de la même famille et leurs petits et de quelques mâles. Les petits mâles sont expulsés du groupe lorsqu'il deviennent matures (a deux ans).",
  },
  {
    id: "2",
    name: "girafe",
    imgSrc: "assets/IMGauthor/SAVANE/girafe.jpg",
    audioSrc: "assets/audio/SAVANE/giraffe.mp3",
    color: "orange",
    english: "girafe",
    french:
      "La girafe est l'animal le plus grand de la savane. Elle peut atteindre 5,80 metres. Les girafes dorment debout car si elles dorment par terre elle risqueraient de ne plus pouvoir se relever.",
  },
  {
    id: "3",
    name: "zebre",
    imgSrc: "assets/IMGauthor/SAVANE/zebre.jpg",
    audioSrc: "assets/audio/SAVANE/zebra.mp3",
    color: "noir et blanc",
    english: "zebra",
    french:
      "Sais-tu que les zebres n'ont pas de rayures au depart. Apparament, les zebres avaient développe ces rayures pour eviter de se faire piquer par les mouches et les moustiques.",
  },
  {
    id: "4",
    name: "crocodile",
    imgSrc: "assets/IMGauthor/SAVANE/crocodile.jpg",
    audioSrc: "assets/audio/SAVANE/crocodile.mp3",
    color: "vert",
    english: "crocodile",
    french:
      "les crocodiles pleurent vraiment, mais pas parce qu’ils sont tristes. Ils pleurent souvent en mangeant, pour humidifier les yeux parce qu’ils ont une troisieme paupiere.",
  },
  {
    id: "5",
    name: "chimpanze",
    imgSrc: "assets/IMGauthor/SAVANE/singe.jpg",
    audioSrc: "assets/audio/SAVANE/chimpanze.mp3",
    color: "brun",
    english: "chimpanze",
    french:
      "Les chimpanzes savent se servir de baguettes pour capturer les termites ou les fourmis dans leur cache, de pierres ou de branches pour briser les coquilles des noix.",
  },
]

const FRUITS = [
  {
    id: "2",
    name: "citron",
    imgSrc: "assets/IMGauthor/FRUITS/citron.png",
    audioSrc: "assets/audio/FRUITS/lemon.mp3",
    color: "jaune",
    english: "citron",
  },
  {
    id: "20",
    name: "demi pomme",
    imgSrc: "assets/IMGauthor/FRUITS/pommeM.png",
    audioSrc: "assets/audio/FRUITS/apple.mp3",
    color: "orange",
    english: "orange",
  },
  {
    id: "4",
    name: "pomme",
    imgSrc: "assets/IMGauthor/FRUITS/pomme.png",
    audioSrc: "assets/audio/FRUITS/apple.mp3",
    color: "rouge",
    english: "apple",
  },
  {
    id: "5",
    name: "poire",
    imgSrc: "assets/IMGauthor/FRUITS/poire.png",
    audioSrc: "assets/audio/FRUITS/pear.mp3",
    color: "marron",
    english: "pear",
  },
  {
    id: "21",
    name: "demi poire",
    imgSrc: "assets/IMGauthor/FRUITS/poireM.png",
    audioSrc: "assets/audio/FRUITS/pear.mp3",
    color: "marron",
    english: "pear",
  },
  {
    id: "11",
    name: "pasteque",
    imgSrc: "assets/IMGauthor/FRUITS/pasteque.png",
    audioSrc: "assets/audio/FRUITS/watermelon.mp3",
    color: "vert et rouge",
    english: "watermelon",
  },
  {
    id: "22",
    name: "demi citron",
    imgSrc: "assets/IMGauthor/FRUITS/citronM.png",
    audioSrc: "assets/audio/FRUITS/lemon.mp3",
    color: "jaune",
    english: "lemon",
  },
  {
    id: "16",
    name: "amande",
    imgSrc: "assets/IMGauthor/FRUITS/amande.png",
    audioSrc: "assets/audio/FRUITS/almond.mp3",
    color: "vert",
    english: "almond",
  },
  {
    id: "17",
    name: "carotte",
    imgSrc: "assets/IMGauthor/FRUITS/carotte.png",
    audioSrc: "assets/audio/FRUITS/carrot.mp3",
    color: "orange",
    english: "carrot",
  },
  {
    id: "18",
    name: "pomme de terre",
    imgSrc: "assets/IMGauthor/FRUITS/pommedeterre.png",
    audioSrc: "assets/audio/FRUITS/potatoes.mp3",
    color: "marron",
    english: "potatoes",
  },
  {
    id: "19",
    name: "petit pois",
    imgSrc: "assets/IMGauthor/FRUITS/petitpois.jpg",
    audioSrc: "assets/audio/FRUITS/bean.mp3",
    color: "vert",
    english: "bean",
  },
]

const NUMBERS = [
  {
    id: "0",
    name: "0",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_0.png",
    audioSrc: "assets/audio/NUMBERS/zero.mp3",
    color: "brown",
    english: "zero",
    french: "zero",
  },
  {
    id: "1",
    name: "1",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_1.png",
    audioSrc: "assets/audio/NUMBERS/one.mp3",
    color: "green ",
    english: "one",
    french: "un",
  },
  {
    id: "2",
    name: "2",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_2.png",
    audioSrc: "assets/audio/NUMBERS/two.mp3",
    color: "pink",
    english: "two",
    french: "deux",
  },
  {
    id: "3",
    name: "3",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_3.png",
    audioSrc: "assets/audio/NUMBERS/three.mp3",
    color: "red",
    english: "three",
    french: "trois",
  },
  {
    id: "4",
    name: "4",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_4.png",
    audioSrc: "assets/audio/NUMBERS/four.mp3",
    color: "blue",
    english: "four",
    french: "quatre",
  },
  {
    id: "5",
    name: "5",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_5.png",
    audioSrc: "assets/audio/NUMBERS/five.mp3",
    color: "orange",
    english: "five",
    french: "cinq",
  },
  {
    id: "6",
    name: "6",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_6.png",
    audioSrc: "assets/audio/NUMBERS/six.mp3",
    color: "light green ",
    english: "six",
    french: "six",
  },
  {
    id: "7",
    name: "7",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_7.png",
    audioSrc: "assets/audio/NUMBERS/seven.mp3",
    color: "yellow",
    english: "seven",
    french: "sept",
  },
  {
    id: "8",
    name: "8",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_8.png",
    audioSrc: "assets/audio/NUMBERS/eight.mp3",
    color: "pupple",
    english: "eight",
    french: "huit",
  },
  {
    id: "9",
    name: "9",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_9.png",
    audioSrc: "assets/audio/NUMBERS/nine.mp3",
    color: "light blue",
    english: "nine",
    french: "neuf",
  },
  {
    id: "10",
    name: "10",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_10.png",
    audioSrc: "assets/audio/NUMBERS/ten.mp3",
    color: "red",
    english: "ten",
    french: "dix",
  },
  {
    id: "11",
    name: "11",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_11.png",
    audioSrc: "assets/audio/NUMBERS/eleven.mp3",
    color: "green",
    english: "eleven",
    french: "onze",
  },
]

const ALPHABET = [
  {
    id: "1",
    name: "A",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_A.png",
    audioSrc: "assets/audio/ALPHABET/a.mp3",
    color: "jaune",
  },
  {
    id: "2",
    name: "B",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_B.png",
    audioSrc: "assets/audio/ALPHABET/b.mp3",
    color: "vert",
  },
  {
    id: "3",
    name: "C",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_C.png",
    audioSrc: "assets/audio/ALPHABET/c.mp3",
    color: "bordeaux",
  },
  {
    id: "4",
    name: "D",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_D.png",
    audioSrc: "assets/audio/ALPHABET/d.mp3",
    color: "bleu",
  },
  {
    id: "5",
    name: "E",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_E.png",
    audioSrc: "assets/audio/ALPHABET/e.mp3",
    color: "orange",
  },
  {
    id: "6",
    name: "F",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_F.png",
    audioSrc: "assets/audio/ALPHABET/f.mp3",
    color: "vert clair",
  },
  {
    id: "7",
    name: "G",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_G.png",
    audioSrc: "assets/audio/ALPHABET/g.mp3",
    color: "jaune",
  },
  {
    id: "8",
    name: "H",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_H.png",
    audioSrc: "assets/audio/ALPHABET/h.mp3",
    color: "violet",
  },
  {
    id: "9",
    name: "I",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_I.png",
    audioSrc: "assets/audio/ALPHABET/i.mp3",
    color: "turquoise",
  },
  {
    id: "10",
    name: "J",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_J.png",
    audioSrc: "assets/audio/ALPHABET/j.mp3",
    color: "rouge",
  },
  {
    id: "11",
    name: "K",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_K.png",
    audioSrc: "assets/audio/ALPHABET/k.mp3",
    color: "",
  },
  {
    id: "12",
    name: "L",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_L.png",
    audioSrc: "assets/audio/ALPHABET/l.mp3",
    color: "vert",
  },
  {
    id: "13",
    name: "M",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_M.png",
    audioSrc: "assets/audio/ALPHABET/m.mp3",
    color: "rouge",
  },
  {
    id: "14",
    name: "N",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_N.png",
    audioSrc: "assets/audio/ALPHABET/n.mp3",
    color: "turquoise",
  },
  {
    id: "15",
    name: "O",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_O.png",
    audioSrc: "assets/audio/ALPHABET/o.mp3",
    color: "orange",
  },
  {
    id: "16",
    name: "P",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_P.png",
    audioSrc: "assets/audio/ALPHABET/p.mp3",
    color: "vert clair",
  },
  {
    id: "17",
    name: "Q",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_Q.png",
    audioSrc: "assets/audio/ALPHABET/q.mp3",
    color: "jaune",
  },
  {
    id: "18",
    name: "R",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_R.png",
    audioSrc: "assets/audio/ALPHABET/r.mp3",
    color: "purple",
  },
  {
    id: "19",
    name: "S",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_S.png",
    audioSrc: "assets/audio/ALPHABET/s.mp3",
    color: "bleu clair",
  },
  {
    id: "20",
    name: "T",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_T.png",
    audioSrc: "assets/audio/ALPHABET/t.mp3",
    color: "rose orange",
  },
  {
    id: "21",
    name: "U",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_U.png",
    audioSrc: "assets/audio/ALPHABET/u.mp3",
    color: "jaune",
  },
  {
    id: "22",
    name: "V",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_V.png",
    audioSrc: "assets/audio/ALPHABET/v.mp3",
    color: "vert",
  },
  {
    id: "23",
    name: "W",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_W.png",
    audioSrc: "assets/audio/ALPHABET/w.mp3",
    color: "rouge",
  },
  {
    id: "24",
    name: "X",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_X.png",
    audioSrc: "assets/audio/ALPHABET/x.mp3",
    color: "bleu",
  },
  {
    id: "25",
    name: "Y",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_Y.png",
    audioSrc: "assets/audio/ALPHABET/y.mp3",
    color: "orange",
  },
  {
    id: "26",
    name: "Z",
    imgSrc: "assets/IMGauthor/ALPHABET/animal_alphabet_Z.png",
    audioSrc: "assets/audio/ALPHABET/z.mp3",
    color: "vert clair",
  },
]

export { SAVANE, FRUITS, NUMBERS, ALPHABET }
