const SAVANE = [
  {
    id: "1",
    name: "lion",
    imgSrc: "IMGauthor/SAVANE/lion.jpg",
    color: "jaune",
    english: "lion",
    french:
      "Les lion vivent en groupe de femelles souvent de la même famille et leurs petits et de quelques mâles. Les petits mâles sont expulsés du groupe lorsqu'il deviennent matures (a deux ans).",
  },
  {
    id: "2",
    name: "girafe",
    imgSrc: "IMGauthor/SAVANE/girafe.jpg",
    color: "orange",
    english: "girafe",
    french:
      "La girafe est l'animal le plus grand de la savane. Elle peut atteindre 5,80 metres. Les girafes dorment debout car si elles dorment par terre elle risqueraient de ne plus pouvoir se relever.",
  },
  {
    id: "3",
    name: "zebre",
    imgSrc: "IMGauthor/SAVANE/zebre.jpg",
    color: "noir et blanc",
    english: "zebra",
    french:
      "Sais-tu que les zebres n'ont pas de rayures au depart. Apparament, les zebres avaient développe ces rayures pour eviter de se faire piquer par les mouches et les moustiques.",
  },
  {
    id: "4",
    name: "crocodile",
    imgSrc: "IMGauthor/SAVANE/crocodile.jpg",
    color: "vert",
    english: "crocodile",
    french:
      "les crocodiles pleurent vraiment, mais pas parce qu’ils sont tristes. Ils pleurent souvent en mangeant, pour humidifier les yeux parce qu’ils ont une troisieme paupiere.",
  },
  {
    id: "5",
    name: "chimpanze",
    imgSrc: "IMGauthor/SAVANE/singe.jpg",
    color: "brun",
    english: "chimpanze",
    french:
      "Les chimpanzes savent se servir de baguettes pour capturer les termites ou les fourmis dans leur cache, de pierres ou de branches pour briser les coquilles des noix.",
  },
]

const FRUITS = [
  {
    id: "1",
    name: "Avocat",
    imgSrc: "IMGauthor/FRUITS/avocat.jpg",
    color: "vert foncé",
    english: "avocado",
  },
  {
    id: "2",
    name: "Citron",
    imgSrc: "IMGauthor/FRUITS/citron.jpg",
    color: "jaune",
    english: "citron",
  },
  {
    id: "3",
    name: "orange",
    imgSrc: "IMGauthor/FRUITS/orange.jpg",
    color: "orange",
    english: "orange",
  },
  {
    id: "4",
    name: "pomme",
    imgSrc: "IMGauthor/FRUITS/pomme.jpg",
    color: "rouge",
    english: "apple",
  },
  {
    id: "5",
    name: "poire",
    imgSrc: "IMGauthor/FRUITS/poire.jpg",
    color: "marron",
    english: "pear",
  },
  {
    id: "6",
    name: "peche",
    imgSrc: "IMGauthor/FRUITS/peche.jpg",
    color: "rouge",
    english: "peach",
  },
  {
    id: "7",
    name: "melon",
    imgSrc: "IMGauthor/FRUITS/melon.jpg",
    color: "orange",
    english: "melon",
  },
  {
    id: "8",
    name: "fraise",
    imgSrc: "IMGauthor/FRUITS/fraise.jpg",
    color: "rouge",
    english: "strawberry",
  },
  {
    id: "9",
    name: "cerise",
    imgSrc: "IMGauthor/FRUITS/cerise.jpg",
    color: "rouge",
    english: "cherry",
  },
  {
    id: "10",
    name: "mure",
    imgSrc: "IMGauthor/FRUITS/mure.jpg",
    color: "violet",
    english: "mulberry",
  },
  {
    id: "11",
    name: "pasteque",
    imgSrc: "IMGauthor/FRUITS/pasteque.jpg",
    color: "vert et rouge",
    english: "watermelon",
  },
  {
    id: "12",
    name: "banane",
    imgSrc: "IMGauthor/FRUITS/banane.jpg",
    color: "jaune",
    english: "banana",
  },
  {
    id: "13",
    name: "mangue",
    imgSrc: "IMGauthor/FRUITS/mangue.jpg",
    color: "jaune",
    english: "mango",
  },
  {
    id: "14",
    name: "kiwi",
    imgSrc: "IMGauthor/FRUITS/kiwi.jpg",
    color: "vert",
    english: "kiwi",
  },
  {
    id: "15",
    name: "pamplemouse",
    imgSrc: "IMGauthor/FRUITS/pamplemouse.jpg",
    color: "rose",
    english: "pomelos",
  },
]

const VEGETABLES = [
  {
    id: "1",
    name: "carotte",
    imgSrc: "IMGauthor/FRUITS/carotte.jpg",
    color: "orange",
    english: "carrot",
  },
  {
    id: "2",
    name: "petits pois",
    imgSrc: "IMGauthor/FRUITS/petitpois.jpg",
    color: "vert",
    french: "green peas",
  },
  {
    id: "3",
    name: "pomme de terre",
    imgSrc: "IMGauthor/FRUITS/pommedeterre.jpg",
    color: "vert foncé",
    english: "potatoes",
  },
  {
    id: "4",
    name: "amande",
    imgSrc: "IMGauthor/FRUITS/amande.jpg",
    color: "vert foncé",
    english: "almond",
  },
]
const NUMBER = [
  {
    id: "0",
    name: "0",
    imgSrc: "IMGauthor/NUMBERS/animal_number_0.png",
    color: "rouge",
    english: "zero",
    french: "zero",
  },
  {
    id: "1",
    name: "1",
    imgSrc: "IMGauthor/NUMBERS/animal_number_1.png",
    color: "vert",
    english: "one",
    french: "un",
  },
  {
    id: "2",
    name: "2",
    imgSrc: "IMGauthor/NUMBERS/animal_number_2.png",
    color: "jaune",
    english: "two",
    french: "deux",
  },
  {
    id: "3",
    name: "3",
    imgSrc: "IMGauthor/NUMBERS/animal_number_3.png",
    color: "rouge",
    english: "three",
    french: "trois",
  },
  {
    id: "4",
    name: "4",
    imgSrc: "IMGauthor/NUMBERS/animal_number_4.png",
    color: "bleu",
    english: "four",
    french: "quatre",
  },
  {
    id: "5",
    name: "5",
    imgSrc: "IMGauthor/NUMBERS/animal_number_5.png",
    color: "orange",
    english: "five",
    french: "cinq",
  },
  {
    id: "6",
    name: "6",
    imgSrc: "IMGauthor/NUMBERS/animal_number_6.png",
    color: "vert clair",
    english: "six",
    french: "six",
  },
  {
    id: "7",
    name: "7",
    imgSrc: "IMGauthor/NUMBERS/animal_number_7.png",
    color: "jaune",
    english: "seven",
    french: "sept",
  },
  {
    id: "8",
    name: "8",
    imgSrc: "IMGauthor/NUMBERS/animal_number_8.png",
    color: "violet",
    english: "eight",
    french: "huit",
  },
  {
    id: "9",
    name: "9",
    imgSrc: "IMGauthor/NUMBERS/animal_number_9.png",
    color: "turquoise",
    english: "nine",
    french: "neuf",
  },
]

const ALPHABET = [
  {
    id: "1",
    name: "A",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_A.png",
    color: "jaune",
  },
  {
    id: "2",
    name: "B",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_B.png",
    color: "vert",
  },
  {
    id: "3",
    name: "C",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_C.png",
    color: "bordeaux",
  },
  {
    id: "4",
    name: "D",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_D.png",
    color: "bleu",
  },
  {
    id: "5",
    name: "E",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_E.png",
    color: "orange",
  },
  {
    id: "6",
    name: "F",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_F.png",
    color: "vert clair",
  },
  {
    id: "7",
    name: "G",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_G.png",
    color: "jaune",
  },
  {
    id: "8",
    name: "H",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_H.png",
    color: "violet",
  },
  {
    id: "9",
    name: "I",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_I.png",
    color: "turquoise",
  },
  {
    id: "10",
    name: "J",
    imgSrc: "IMGauthor/alphabet/animal_alphabetJ.png",
    color: "rouge",
  },
  {
    id: "11",
    name: "K",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_K.png",
    color: "",
  },
  {
    id: "12",
    name: "L",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_L.png",
    color: "vert",
  },
  {
    id: "13",
    name: "M",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_M.png",
    color: "rouge",
  },
  {
    id: "14",
    name: "N",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_N.png",
    color: "turquoise",
  },
  {
    id: "15",
    name: "O",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_O.png",
    color: "orange",
  },
  {
    id: "16",
    name: "P",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_P.png",
    color: "vert clair",
  },
  {
    id: "17",
    name: "Q",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_Q.png",
    color: "jaune",
  },
  {
    id: "18",
    name: "R",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_R.png",
    color: "purple",
  },
  {
    id: "19",
    name: "S",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_S.png",
    color: "bleu clair",
  },
  {
    id: "20",
    name: "T",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_T.png",
    color: "rose orange",
  },
  {
    id: "21",
    name: "U",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_U.png",
    color: "jaune",
  },
  {
    id: "22",
    name: "V",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_V.png",
    color: "vert",
  },
  {
    id: "23",
    name: "W",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_W.png",
    color: "rouge",
  },
  {
    id: "24",
    name: "X",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_X.png",
    color: "bleu",
  },
  {
    id: "25",
    name: "Y",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_Y.png",
    color: "orange",
  },
  {
    id: "26",
    name: "Z",
    imgSrc: "IMGauthor/alphabet/animal_alphabet_Z.png",
    color: "vert clair",
  },
]

export { SAVANE, FRUITS, VEGETABLES, NUMBER, ALPHABET }
