export default [
  {
    id: "2",
    name: "citron",
    imgSrc: "assets/IMGauthor/FRUITS/citron.png",
    audioSrc: "assets/audio/FRUITS/lemon.mp3",
    color: "jaune",
    english: "citron",
  },
  {
    id: "20",
    name: "demi pomme",
    imgSrc: "assets/IMGauthor/FRUITS/pommeM.png",
    audioSrc: "assets/audio/FRUITS/apple.mp3",
    color: "orange",
    english: "orange",
  },
  {
    id: "4",
    name: "pomme",
    imgSrc: "assets/IMGauthor/FRUITS/pomme.png",
    audioSrc: "assets/audio/FRUITS/apple.mp3",
    color: "rouge",
    english: "apple",
  },
  {
    id: "5",
    name: "poire",
    imgSrc: "assets/IMGauthor/FRUITS/poire.png",
    audioSrc: "assets/audio/FRUITS/pear.mp3",
    color: "marron",
    english: "pear",
  },
  {
    id: "21",
    name: "demi poire",
    imgSrc: "assets/IMGauthor/FRUITS/poireM.png",
    audioSrc: "assets/audio/FRUITS/pear.mp3",
    color: "marron",
    english: "pear",
  },
  {
    id: "11",
    name: "pasteque",
    imgSrc: "assets/IMGauthor/FRUITS/pasteque.png",
    audioSrc: "assets/audio/FRUITS/watermelon.mp3",
    color: "vert et rouge",
    english: "watermelon",
  },
  {
    id: "22",
    name: "demi citron",
    imgSrc: "assets/IMGauthor/FRUITS/citronM.png",
    audioSrc: "assets/audio/FRUITS/lemon.mp3",
    color: "jaune",
    english: "lemon",
  },
  {
    id: "16",
    name: "amande",
    imgSrc: "assets/IMGauthor/FRUITS/amande.png",
    audioSrc: "assets/audio/FRUITS/almond.mp3",
    color: "vert",
    english: "almond",
  },
  {
    id: "17",
    name: "carotte",
    imgSrc: "assets/IMGauthor/FRUITS/carotte.png",
    audioSrc: "assets/audio/FRUITS/carrot.mp3",
    color: "orange",
    english: "carrot",
  },
  {
    id: "18",
    name: "pomme de terre",
    imgSrc: "assets/IMGauthor/FRUITS/pommedeterre.png",
    audioSrc: "assets/audio/FRUITS/potatoes.mp3",
    color: "marron",
    english: "potatoes",
  },
  {
    id: "19",
    name: "petit pois",
    imgSrc: "assets/IMGauthor/FRUITS/petitpois.jpg",
    audioSrc: "assets/audio/FRUITS/bean.mp3",
    color: "vert",
    english: "bean",
  },
]
