export default [
  {
    id: "0",
    name: "0",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_0.png",
    audioSrc: "assets/audio/NUMBERS/zero.mp3",
    color: "brown",
    english: "zero",
    french: "zero",
  },
  {
    id: "1",
    name: "1",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_1.png",
    audioSrc: "assets/audio/NUMBERS/one.mp3",
    color: "green ",
    english: "one",
    french: "un",
  },
  {
    id: "2",
    name: "2",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_2.png",
    audioSrc: "assets/audio/NUMBERS/two.mp3",
    color: "pink",
    english: "two",
    french: "deux",
  },
  {
    id: "3",
    name: "3",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_3.png",
    audioSrc: "assets/audio/NUMBERS/three.mp3",
    color: "red",
    english: "three",
    french: "trois",
  },
  {
    id: "4",
    name: "4",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_4.png",
    audioSrc: "assets/audio/NUMBERS/four.mp3",
    color: "blue",
    english: "four",
    french: "quatre",
  },
  {
    id: "5",
    name: "5",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_5.png",
    audioSrc: "assets/audio/NUMBERS/five.mp3",
    color: "orange",
    english: "five",
    french: "cinq",
  },
  {
    id: "6",
    name: "6",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_6.png",
    audioSrc: "assets/audio/NUMBERS/six.mp3",
    color: "light green ",
    english: "six",
    french: "six",
  },
  {
    id: "7",
    name: "7",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_7.png",
    audioSrc: "assets/audio/NUMBERS/seven.mp3",
    color: "yellow",
    english: "seven",
    french: "sept",
  },
  {
    id: "8",
    name: "8",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_8.png",
    audioSrc: "assets/audio/NUMBERS/eight.mp3",
    color: "pupple",
    english: "eight",
    french: "huit",
  },
  {
    id: "9",
    name: "9",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_9.png",
    audioSrc: "assets/audio/NUMBERS/nine.mp3",
    color: "light blue",
    english: "nine",
    french: "neuf",
  },
  {
    id: "10",
    name: "10",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_10.png",
    audioSrc: "assets/audio/NUMBERS/ten.mp3",
    color: "red",
    english: "ten",
    french: "dix",
  },
  {
    id: "11",
    name: "11",
    imgSrc: "assets/IMGauthor/NUMBERS/animal_number_11.png",
    audioSrc: "assets/audio/NUMBERS/eleven.mp3",
    color: "green",
    english: "eleven",
    french: "onze",
  },
]
